[package]
name = "nwg-tray-demo"
version = "0.1.0"
edition.workspace = true

[dependencies]
native-windows-gui.workspace = true
native-windows-gui.features = ["tray-notification", "message-window", "menu", "cursor", "clipboard"]
winapi.workspace = true
thiserror.workspace = true
